<?php
  declare(strict_types=1);

	namespace Fawno\Calameo\Book;

	class Languages {
		public const unknown = 'unknown';
		public const en = 'en';
		public const fr = 'fr';
		public const de = 'de';
		public const es = 'es';
		public const it = 'it';
		public const pt = 'pt';
		public const ja = 'ja';
		public const zh = 'zh';
		public const hi = 'hi';
		public const aa = 'aa';
		public const ab = 'ab';
		public const ae = 'ae';
		public const af = 'af';
		public const ak = 'ak';
		public const am = 'am';
		public const an = 'an';
		public const ar = 'ar';
		public const as = 'as';
		public const av = 'av';
		public const ay = 'ay';
		public const az = 'az';
		public const ba = 'ba';
		public const be = 'be';
		public const bg = 'bg';
		public const bh = 'bh';
		public const bi = 'bi';
		public const bm = 'bm';
		public const bn = 'bn';
		public const bo = 'bo';
		public const br = 'br';
		public const bs = 'bs';
		public const ca = 'ca';
		public const ce = 'ce';
		public const ch = 'ch';
		public const co = 'co';
		public const cr = 'cr';
		public const cs = 'cs';
		public const cu = 'cu';
		public const cv = 'cv';
		public const cy = 'cy';
		public const da = 'da';
		public const dv = 'dv';
		public const dz = 'dz';
		public const ee = 'ee';
		public const el = 'el';
		public const eo = 'eo';
		public const et = 'et';
		public const eu = 'eu';
		public const fa = 'fa';
		public const ff = 'ff';
		public const fi = 'fi';
		public const fj = 'fj';
		public const fo = 'fo';
		public const fy = 'fy';
		public const ga = 'ga';
		public const gd = 'gd';
		public const gl = 'gl';
		public const gn = 'gn';
		public const gu = 'gu';
		public const gv = 'gv';
		public const ha = 'ha';
		public const he = 'he';
		public const ho = 'ho';
		public const hr = 'hr';
		public const ht = 'ht';
		public const hu = 'hu';
		public const hy = 'hy';
		public const hz = 'hz';
		public const ia = 'ia';
		public const id = 'id';
		public const ie = 'ie';
		public const ig = 'ig';
		public const ii = 'ii';
		public const ik = 'ik';
		public const io = 'io';
		public const is = 'is';
		public const iu = 'iu';
		public const jv = 'jv';
		public const ka = 'ka';
		public const kg = 'kg';
		public const ki = 'ki';
		public const kj = 'kj';
		public const kk = 'kk';
		public const kl = 'kl';
		public const km = 'km';
		public const kn = 'kn';
		public const ko = 'ko';
		public const kr = 'kr';
		public const ks = 'ks';
		public const ku = 'ku';
		public const kv = 'kv';
		public const kw = 'kw';
		public const ky = 'ky';
		public const la = 'la';
		public const lb = 'lb';
		public const lg = 'lg';
		public const li = 'li';
		public const ln = 'ln';
		public const lo = 'lo';
		public const lt = 'lt';
		public const lu = 'lu';
		public const lv = 'lv';
		public const mg = 'mg';
		public const mh = 'mh';
		public const mi = 'mi';
		public const mk = 'mk';
		public const ml = 'ml';
		public const mn = 'mn';
		public const mo = 'mo';
		public const mr = 'mr';
		public const ms = 'ms';
		public const mt = 'mt';
		public const my = 'my';
		public const na = 'na';
		public const nb = 'nb';
		public const nd = 'nd';
		public const ne = 'ne';
		public const ng = 'ng';
		public const nl = 'nl';
		public const nn = 'nn';
		public const no = 'no';
		public const nr = 'nr';
		public const nv = 'nv';
		public const ny = 'ny';
		public const oc = 'oc';
		public const oj = 'oj';
		public const om = 'om';
		public const or = 'or';
		public const os = 'os';
		public const pa = 'pa';
		public const pi = 'pi';
		public const pl = 'pl';
		public const ps = 'ps';
		public const qu = 'qu';
		public const rm = 'rm';
		public const rn = 'rn';
		public const ro = 'ro';
		public const ru = 'ru';
		public const rw = 'rw';
		public const sa = 'sa';
		public const sc = 'sc';
		public const sd = 'sd';
		public const se = 'se';
		public const sg = 'sg';
		public const sh = 'sh';
		public const si = 'si';
		public const sk = 'sk';
		public const sl = 'sl';
		public const sm = 'sm';
		public const sn = 'sn';
		public const so = 'so';
		public const sq = 'sq';
		public const sr = 'sr';
		public const ss = 'ss';
		public const st = 'st';
		public const su = 'su';
		public const sv = 'sv';
		public const sw = 'sw';
		public const ta = 'ta';
		public const te = 'te';
		public const tg = 'tg';
		public const th = 'th';
		public const ti = 'ti';
		public const tk = 'tk';
		public const tl = 'tl';
		public const tn = 'tn';
		public const to = 'to';
		public const tr = 'tr';
		public const ts = 'ts';
		public const tt = 'tt';
		public const tw = 'tw';
		public const ty = 'ty';
		public const ug = 'ug';
		public const uk = 'uk';
		public const ur = 'ur';
		public const uz = 'uz';
		public const ve = 've';
		public const vi = 'vi';
		public const vo = 'vo';
		public const wa = 'wa';
		public const wo = 'wo';
		public const xh = 'xh';
		public const yi = 'yi';
		public const yo = 'yo';
		public const za = 'za';
		public const zu = 'zu';

		/**
		 * Language (dialect)
		 * http://help.calameo.com/index.php?title=API:Language_(references)
		*/
		public const LANGUAGES = [
			self::unknown => 'Unknown',
			self::en => 'English',
			self::fr => 'French',
			self::de => 'German',
			self::es => 'Spanish',
			self::it => 'Italian',
			self::pt => 'Portuguese',
			self::ja => 'Japanese',
			self::zh => 'Chinese',
			self::hi => 'Hindi',
			self::aa => 'Afar',
			self::ab => 'Abkhaze',
			self::ae => 'Avestan',
			self::af => 'Afrikaans',
			self::ak => 'Akan',
			self::am => 'Amharic',
			self::an => 'Aragonese',
			self::ar => 'Arabic',
			self::as => 'Assamese',
			self::av => 'Avaric',
			self::ay => 'Aymara',
			self::az => 'Azerbaijani',
			self::ba => 'Bashkir',
			self::be => 'Belarusian',
			self::bg => 'Bulgarian',
			self::bh => 'Bihari',
			self::bi => 'Bislama',
			self::bm => 'Bambara',
			self::bn => 'Bengali',
			self::bo => 'Tibetan',
			self::br => 'Breton',
			self::bs => 'Bosnian',
			self::ca => 'Catalan',
			self::ce => 'Chechen',
			self::ch => 'Chamorro',
			self::co => 'Corsican',
			self::cr => 'Cree',
			self::cs => 'Czech',
			self::cu => 'Church Slavic',
			self::cv => 'Chuvash',
			self::cy => 'Welsh',
			self::da => 'Danish',
			self::dv => 'Divehi',
			self::dz => 'Dzongkha',
			self::ee => 'Ewe',
			self::el => 'Greek',
			self::eo => 'Esperanto',
			self::et => 'Estonian',
			self::eu => 'Basque',
			self::fa => 'Persian',
			self::ff => 'Fulah',
			self::fi => 'Finnish',
			self::fj => 'Fijian',
			self::fo => 'Faroese',
			self::fy => 'Western Frisian',
			self::ga => 'Irish',
			self::gd => 'Scottish Gaelic',
			self::gl => 'Galician',
			self::gn => 'Guaraní',
			self::gu => 'Gujarati',
			self::gv => 'Manx',
			self::ha => 'Hausa',
			self::he => 'Hebrew',
			self::ho => 'Hiri Motu',
			self::hr => 'Croatian',
			self::ht => 'Haitian',
			self::hu => 'Hungarian',
			self::hy => 'Armenian',
			self::hz => 'Herero',
			self::ia => 'Interlingua',
			self::id => 'Indonesian',
			self::ie => 'Interlingue',
			self::ig => 'Igbo',
			self::ii => 'Sichuan Yi',
			self::ik => 'Inupiaq',
			self::io => 'Ido',
			self::is => 'Icelandic',
			self::iu => 'Inuktitut',
			self::jv => 'Javanese',
			self::ka => 'Georgian',
			self::kg => 'Kongo',
			self::ki => 'Kikuyu',
			self::kj => 'Kwanyama',
			self::kk => 'Kazakh',
			self::kl => 'Kalaallisut',
			self::km => 'Khmer',
			self::kn => 'Kannada',
			self::ko => 'Korean',
			self::kr => 'Kanuri',
			self::ks => 'Kashmiri',
			self::ku => 'Kurdish',
			self::kv => 'Komi',
			self::kw => 'Cornish',
			self::ky => 'Kirghiz',
			self::la => 'Latin',
			self::lb => 'Luxembourgish',
			self::lg => 'Ganda',
			self::li => 'Limburgish',
			self::ln => 'Lingala',
			self::lo => 'Lao',
			self::lt => 'Lithuanian',
			self::lu => 'Luba-Katanga',
			self::lv => 'Latvian',
			self::mg => 'Malagasy',
			self::mh => 'Marshallese',
			self::mi => 'Ma-ori',
			self::mk => 'Macedonian',
			self::ml => 'Malayalam',
			self::mn => 'Mongolian',
			self::mo => 'Moldavian',
			self::mr => 'Marathi',
			self::ms => 'Malay',
			self::mt => 'Maltese',
			self::my => 'Burmese',
			self::na => 'Nauru',
			self::nb => 'Norwegian Bokmål',
			self::nd => 'North Ndebele',
			self::ne => 'Nepali',
			self::ng => 'Ndonga',
			self::nl => 'Dutch',
			self::nn => 'Norwegian Nynorsk',
			self::no => 'Norwegian',
			self::nr => 'South Ndebele',
			self::nv => 'Navajo',
			self::ny => 'Chichewa',
			self::oc => 'Occitan',
			self::oj => 'Ojibwa',
			self::om => 'Oromo',
			self::or => 'Oriya',
			self::os => 'Ossetian',
			self::pa => 'Panjabi',
			self::pi => 'Pa-li',
			self::pl => 'Polish',
			self::ps => 'Pashto',
			self::qu => 'Quechua',
			self::rm => 'Raeto-Romance',
			self::rn => 'Kirundi',
			self::ro => 'Romanian',
			self::ru => 'Russian',
			self::rw => 'Kinyarwanda',
			self::sa => 'Sanskrit',
			self::sc => 'Sardinian',
			self::sd => 'Sindhi',
			self::se => 'Northern Sami',
			self::sg => 'Sango',
			self::sh => 'Serbo-Croatian',
			self::si => 'Sinhalese',
			self::sk => 'Slovak',
			self::sl => 'Slovenian',
			self::sm => 'Samoan',
			self::sn => 'Shona',
			self::so => 'Somali',
			self::sq => 'Albanian',
			self::sr => 'Serbian',
			self::ss => 'Swati',
			self::st => 'Sotho',
			self::su => 'Sundanese',
			self::sv => 'Swedish',
			self::sw => 'Swahili',
			self::ta => 'Tamil',
			self::te => 'Telugu',
			self::tg => 'Tajik',
			self::th => 'Thai',
			self::ti => 'Tigrinya',
			self::tk => 'Turkmen',
			self::tl => 'Tagalog',
			self::tn => 'Tswana',
			self::to => 'Tonga',
			self::tr => 'Turkish',
			self::ts => 'Tsonga',
			self::tt => 'Tatar',
			self::tw => 'Twi',
			self::ty => 'Tahitian',
			self::ug => 'Uighur',
			self::uk => 'Ukrainian',
			self::ur => 'Urdu',
			self::uz => 'Uzbek',
			self::ve => 'Venda',
			self::vi => 'Vietnamese',
			self::vo => 'Volapük',
			self::wa => 'Walloon',
			self::wo => 'Wolof',
			self::xh => 'Xhosa',
			self::yi => 'Yiddish',
			self::yo => 'Yoruba',
			self::za => 'Zhuang',
			self::zu => 'Zulu',
		];
	}
